### ISSUE TITLE
Is Python required for this plugin?

### ISSUE THREAD

**Issue by SimonEast** [Sonaryr/eleventy-plugin-sass#25]
Is Python 2 required to run this package? I have Python 3.7.4 installed, but I am getting errors (see below). There was nothing in the notes or installation steps about python, so just thought I'd check. If it's a dependency, perhaps it could be listed in the README.

```
D:\Dev\Eleventy-Test>npm install eleventy-plugin-sass --save
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path D:\Dev\Eleventy-Test\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe D:\Dev\Eleventy-Test\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'D:\\Dev\\Eleventy-Test\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.10.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Dev\Eleventy-Test\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Dev\Eleventy-Test\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Dev\Eleventy-Test\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Dev\Eleventy-Test\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Dev\Eleventy-Test\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Dev\Eleventy-Test\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (D:\Dev\Eleventy-Test\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (D:\Dev\Eleventy-Test\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (D:\Dev\Eleventy-Test\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at D:\Dev\Eleventy-Test\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at D:\Dev\Eleventy-Test\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at D:\Dev\Eleventy-Test\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:196:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\Simon\AppData\Local\Programs\Python\Python37\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\Simon\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                                ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Dev\\Eleventy-Test\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd D:\Dev\Eleventy-Test\node_modules\node-sass
npm ERR! gyp ERR! node -v v15.10.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
```

**Comment by SimonEast** [comment]
I couldn't get this plugin to work, so I instead went with a relatively clean and simple sass setup as described [here](https://www.belter.io/eleventy-sass-workflow/). It has less dependencies, uses the updated dart sass library rather than the deprecated "libsass" which seems to be used here, and worked out of the box.
